name: New Token Test

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Test with NEW AppToken
      run: |
        echo "=== Testing with NEW AppToken ==="
        echo "New AppToken: AT_oVgZnjiSqzzv1ycEbihcgjtoM4BggMjz"
        echo "Time: $(date)"
        
        response=$(curl -s -X POST "https://wxpusher.zjiecode.com/api/send/message" \
          -H "Content-Type: application/json" \
          -d '{
            "appToken": "AT_oVgZnjiSqzzv1ycEbihcgjtoM4BggMjz",
            "content": "🎉 NEW TOKEN TEST SUCCESS!\n\n⏰ Time: '"$(date)"'\n✅ Status: Using NEW AppToken\n🔑 New Token: AT_oVgZnjiSqzzv1ycEbihcgjtoM4BggMjz\n📱 This should work now!",
            "summary": "New Token Test - SUCCESS",
            "contentType": 1,
            "uids": ["UID_Nkv98Q7XEQcDsvSInIlR10nm33xI"]
          }')
        
        echo "Response: $response"
        echo "✅ Test with new token completed!"
        
    - name: Verify Response
      run: |
        echo "If you received this notification, the issue is FIXED!"
        echo "Please check your WXpusher now."