name: Simple Test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Send Test Notification
      run: |
        echo "Sending test notification..."
        
        # 最简单的通知内容，避免编码问题
        curl -s -X POST "https://wxpusher.zjiecode.com/api/send/message" \
          -H "Content-Type: application/json" \
          -d '{"appToken":"AT_oVgZnjiSqzzv1ycEbihcgjtoM4BggMjz","content":"Simple Test - CS2 Monitor Working","summary":"Test Notification","contentType":1,"uids":["UID_Nkv98Q7XEQcDsvSInIlR10nm33xI"]}'
        
        echo "Notification response:"